--DROP SCHEMA PRODUCTO;
--DROP SCHEMA TRANSACCION;
--DROP USER netby_user;
USE master;
GO
CREATE LOGIN netby_user WITH PASSWORD = 'mSGAifYo@vQ2P!NFhAy';
GO
CREATE DATABASE netby_test;
GO
USE netby_test;
GO
CREATE USER netby_user FOR LOGIN netby_user;
ALTER ROLE db_owner ADD MEMBER netby_user;
SELECT name, type_desc FROM sys.database_principals WHERE name = 'netby_user';
GO
CREATE SCHEMA PRODUCTO;
GO
--CREATE SCHEMA SUJETO;
GO
CREATE SCHEMA TRANSACCION;
GO
CREATE TABLE PRODUCTO.CATEGORIA (
	ID int NOT NULL IDENTITY(1,1),
	NOMBRE nvarchar(250) COLLATE Latin1_General_CI_AS NOT NULL ,
	ESTADO bit NOT NULL,
	CONSTRAINT PK_CATEGORIA PRIMARY KEY(ID)
);

CREATE TABLE PRODUCTO.PRODUCTOS (
	ID INT NOT NULL IDENTITY(1,1),
	NOMBRE NVARCHAR(250) COLLATE Latin1_General_CI_AS NOT NULL,
	DESCRIPCION NVARCHAR(500) COLLATE Latin1_General_CI_AS NOT NULL,
	IMAGEN NVARCHAR(250) COLLATE Latin1_General_CI_AS NOT NULL,
	PRECIO DECIMAL(6,4) NOT NULL,
	STOCK INT NOT NULL,
	CATEGORIA_ID INT NOT NULL,
	CONSTRAINT PK_PRODUCTO PRIMARY KEY(ID),
	CONSTRAINT FK_PRODUCTO_CATEGORIA FOREIGN KEY (CATEGORIA_ID) REFERENCES PRODUCTO.CATEGORIA(ID)
);


--CREATE TABLE SUJETO.ROL (
--	ID INT NOT NULL IDENTITY(1,1),
--	NOMBRE NVARCHAR(100) NOT NULL,
--	ESTADO BIT NOT NULL
--	CONSTRAINT PK_ROL PRIMARY KEY (ID)
--);
--
--CREATE TABLE SUJETO.USUARIO (
--	ID INT NOT NULL IDENTITY (1,1),
--	NOMBRE NVARCHAR(250) COLLATE Latin1_General_CI_AS NOT NULL ,
--	USUARIO NVARCHAR(250) COLLATE Latin1_General_CI_AS NOT NULL ,
--	CLAVE NVARCHAR(250) COLLATE Latin1_General_CI_AS NOT NULL ,
--	ROL_ID INT NOT NULL,
--	ESTADO BIT NOT NULL,
--	CONSTRAINT PK_USUARIO PRIMARY KEY (ID),
--	CONSTRAINT FK_USUARIO_ROL FOREIGN KEY (ROL_ID) REFERENCES SUJETO.ROL (ID)
--);


CREATE TABLE TRANSACCION.TIPO_TRANSACCION (
	ID INT NOT NULL IDENTITY(1,1),
	ESTADO BIT NOT NULL
	CONSTRAINT PK_TIPO_TRANSACCION PRIMARY KEY (ID)
);

CREATE TABLE TRANSACCION.TRANSACCIONES (
	ID INT NOT NULL IDENTITY(1,1),
	FECHA DATE NOT NULL,
	CANTIDAD INT NOT NULL,
	PRECIO_UNITARIO DECIMAL(6,4) NOT NULL,
	PRECIO_TOTAL DECIMAL(6,4) NOT NULL,
	DETALLE NVARCHAR(500) COLLATE Latin1_General_CI_AS NOT NULL ,
	TIPO_TRANSACCION_ID INT NOT NULL,
	PRODUCTO_ID INT NOT NULL,
--	USUARIO_ID INT NOT NULL,
	CONSTRAINT PK_TRANSACCION PRIMARY KEY (ID),
	CONSTRAINT FK_TRANSACCION_TIPO_TRANS FOREIGN KEY (TIPO_TRANSACCION_ID) REFERENCES TRANSACCION.TIPO_TRANSACCION (ID),
	CONSTRAINT FK_TRANSACCION_PRODUCTO FOREIGN KEY (PRODUCTO_ID) REFERENCES PRODUCTO.PRODUCTOS (ID),
--	CONSTRAINT FK_TRANSACCION_USUARIO FOREIGN KEY (USUARIO_ID) REFERENCES SUJETO.USUARIO (ID),
);

SELECT * FROM TRANSACCION.TRANSACCIONES;